name: node-builder

on:
  pull_request:
    branches:
      - master
    paths:
      - 'node/Dockerfile.builder'

jobs:
  build:
    name: docker image for node-builder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_major_version: [10, 12]
    steps:
    - name: ... docker login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: ... git checkout
      uses: actions/checkout@v1

    - name: ... docker build node ${{ matrix.node_major_version }} builder image
      run: bash ./build.sh
      env:
        DOCKERFILE: Dockerfile.builder
        GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMG_TYPE: node
        SHELL_IN_CON: sh
        NODE_MAJOR_VERSION: ${{ matrix.node_major_version }}

# vim: et sr sw=2 ts=2 smartindent:
