name: node-builder

on:
  pull_request:
    branches:
      - master
    paths:
      - 'build.sh'
      - 'node/**'
  push:
    branches:
      - master # if result of merge to master

jobs:
  build:
    if: github.event_name == 'pull_request' && github.base_ref == 'master'
    name: docker image for node-builder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_major_version: [10, 12]
    steps:
    - name: ... docker login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: ... git checkout
      uses: actions/checkout@v1

    - name: ... docker build node ${{ matrix.node_major_version }} builder image
      run: |
        bash build.sh || exit 1
      env:
        DOCKERFILE: Dockerfile.builder
        GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMG_NAME: propero/builder-node${{ matrix.node_major_version }}
        IMG_TAG: ${{ github.sha }}
        IMG_TYPE: node
        NODE_MAJOR_VERSION: ${{ matrix.node_major_version }}
        SHELL_IN_CON: sh

# vim: et sr sw=2 ts=2 smartindent:
# 'build' pushes to docker hub on success using git sha as tag
# this allows 'test' to retrieve the container to test it
# Finally we can on push to master find that sha and retag
# the image for pushing.
